Users.find_or_create_by(name: "Alex", username: "besttraderhere", email: "alex@gmail.com", password_digest: "test")
Users.find_or_create_by(name: "John", username: "jmoney", email: "john@gmail.com", password_digest: "password")
Users.find_or_create_by(name: "Emily", username: "wolfofcrypto", email: "emily@gmail.com", password_digest: "notpassword")

Wallets.find_or_create_by(user_id: 1, name: "My Experimental Wallet", type: "experimental", btc_balance: 1, usd_balance: 1000)
Wallets.find_or_create_by(user_id: 1, name: "My Competitive Wallet", type: "competitive", btc_balance: 0, usd_balance: 90.5)
Wallets.find_or_create_by(user_id: 2, name: "Exerimental Strategy", type: "experimental", btc_balance: 0.5, usd_balance: 500.75)
Wallets.find_or_create_by(user_id: 2, name: "Exerimental Strategy 2", type: "experimental", btc_balance: 2, usd_balance: 10)
Wallets.find_or_create_by(user_id: 3, name: "Comp", type: "competitive", btc_balance: 0, usd_balance: 0)

Transaction.find_or_create_by(wallet_id: 1, type: "buy", amount: 1, price: 10000)
Transaction.find_or_create_by(wallet_id: 1, type: "sell", amount: 1, price: 11000)
Transaction.find_or_create_by(wallet_id: 1, type: "buy", amount: 0.5, price: 10000)
Transaction.find_or_create_by(wallet_id: 1, type: "buy", amount: 0.25, price: 10000)
Transaction.find_or_create_by(wallet_id: 1, type: "buy", amount: 0.25, price: 10000)
Transaction.find_or_create_by(wallet_id: 2, type: "buy", amount: 0.01, price: 10000)
Transaction.find_or_create_by(wallet_id: 2, type: "sell", amount: 0.01, price: 9050)
Transaction.find_or_create_by(wallet_id: 3, type: "buy", amount: 0.05, price: 10000)
Transaction.find_or_create_by(wallet_id: 3, type: "buy", amount: 0.01, price: 10000)
Transaction.find_or_create_by(wallet_id: 3, type: "sell", amount: 0.050075, price: 10000)
Transaction.find_or_create_by(wallet_id: 4, type: "buy", amount: 2, price: 9000)