User.find_or_create_by(name: "Alex", username: "besttraderhere", email: "alex@gmail.com", password_digest: "test")
User.find_or_create_by(name: "John", username: "jmoney", email: "john@gmail.com", password_digest: "password")
User.find_or_create_by(name: "Emily", username: "wolfofcrypto", email: "emily@gmail.com", password_digest: "notpassword")

Wallet.find_or_create_by(user_id: 1, name: "My Experimental Wallet", restriction_type: "experimental", btc_balance: 1, usd_balance: 1000)
Wallet.find_or_create_by(user_id: 1, name: "My Competitive Wallet", restriction_type: "competitive", btc_balance: 0, usd_balance: 90.5)
Wallet.find_or_create_by(user_id: 2, name: "Exerimental Strategy", restriction_type: "experimental", btc_balance: 0.5, usd_balance: 500.75)
Wallet.find_or_create_by(user_id: 2, name: "Exerimental Strategy 2", restriction_type: "experimental", btc_balance: 2, usd_balance: 10)
Wallet.find_or_create_by(user_id: 3, name: "Comp", restriction_type: "competitive", btc_balance: 0, usd_balance: 0)

Transaction.find_or_create_by(wallet_id: 1, order_type: "buy", amount: 1, price: 10000)
Transaction.find_or_create_by(wallet_id: 1, order_type: "sell", amount: 1, price: 11000)
Transaction.find_or_create_by(wallet_id: 1, order_type: "buy", amount: 0.5, price: 10000)
Transaction.find_or_create_by(wallet_id: 1, order_type: "buy", amount: 0.25, price: 10000)
Transaction.find_or_create_by(wallet_id: 1, order_type: "buy", amount: 0.25, price: 10000)
Transaction.find_or_create_by(wallet_id: 2, order_type: "buy", amount: 0.01, price: 10000)
Transaction.find_or_create_by(wallet_id: 2, order_type: "sell", amount: 0.01, price: 9050)
Transaction.find_or_create_by(wallet_id: 3, order_type: "buy", amount: 0.05, price: 10000)
Transaction.find_or_create_by(wallet_id: 3, order_type: "buy", amount: 0.01, price: 10000)
Transaction.find_or_create_by(wallet_id: 3, order_type: "sell", amount: 0.050075, price: 10000)
Transaction.find_or_create_by(wallet_id: 4, order_type: "buy", amount: 2, price: 9000)